// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRRNshmpSsF9UR-K6AdDKFYoFJusEPj9I',
    appId: '1:141640203346:web:ff9f8d3d24bfb651e2738b',
    messagingSenderId: '141640203346',
    projectId: 'chat-app-f3ac1',
    authDomain: 'chat-app-f3ac1.firebaseapp.com',
    storageBucket: 'chat-app-f3ac1.firebasestorage.app',
    measurementId: 'G-GGBV6NW8Y3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSWQDXY3k_bvnM4N1a9HVAUBLuG9zLiAc',
    appId: '1:141640203346:android:2fccbe8b32f2c119e2738b',
    messagingSenderId: '141640203346',
    projectId: 'chat-app-f3ac1',
    storageBucket: 'chat-app-f3ac1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOFUnux5oe7SV1BO1U7orr_xMbC4CENBI',
    appId: '1:141640203346:ios:0c71d657cc55df75e2738b',
    messagingSenderId: '141640203346',
    projectId: 'chat-app-f3ac1',
    storageBucket: 'chat-app-f3ac1.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOFUnux5oe7SV1BO1U7orr_xMbC4CENBI',
    appId: '1:141640203346:ios:0c71d657cc55df75e2738b',
    messagingSenderId: '141640203346',
    projectId: 'chat-app-f3ac1',
    storageBucket: 'chat-app-f3ac1.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRRNshmpSsF9UR-K6AdDKFYoFJusEPj9I',
    appId: '1:141640203346:web:8d132dfba59bc01ce2738b',
    messagingSenderId: '141640203346',
    projectId: 'chat-app-f3ac1',
    authDomain: 'chat-app-f3ac1.firebaseapp.com',
    storageBucket: 'chat-app-f3ac1.firebasestorage.app',
    measurementId: 'G-SSVYZTB9Q8',
  );
}
